site_name: RadMap documentation
theme:
   name: 'material'
   logo: 'img/logo.png'
   favicon: 'img/logo.png'
nav:
   - Installation: installation_instruction.md
   - User guide: index.md
extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - admonition